### ISSUE TITLE
Can get the same PSNR ans SSIM results as reported in the paper

### ISSUE THREAD

**Issue by yJJtiG** [jiangsutx/SRN-Deblur#56]
I can't install tensorflow 1.4 version, and I tested in the tensorflow 1.15 version according to the code and model provided by the authors, ans used the Matlab functions `psnr()` and `ssim()` to calculate the qualitative results. The results are `PSNR = 27.34 dB, SSIM = 0.8952` on GOPRO testing dataset when using --model=lstm, which are far from the results `PSNR = 30.19 dB, SSIM = 0.9334` provided by the authors. I don't know if it's because of different tensorflow versions?

Matlab code is as follows
```
% im_gt: Ground Turth, im_out: Output Image
psnr(im_gt, im_out)
ssim(im_gt, im_out)
```

**Comment by yJJtiG** [comment]
Or could the authors provide the Matlab code for calculating qualitative results?

**Comment by jiangsutx** [comment]
First, please check whether the produced results sharper and clearer than input images ? Make sure it produces reasonable results, rather than artifacts and noise.

Do the output and GT image correspond to the same image, without shift.

I remembder GOPRO dataset contains linear & non-linear version of images. Please try and select the correct one for the pretrained model. We use linear data (no gamma correction) for both training and testing.

**Comment by yJJtiG** [comment]
Thank you for replying quickly. I did use the wrong testing data and got the correct results after modification. Thank you so much.

**Comment by ldlshizhu** [comment]
> Thank you for replying quickly. I did use the wrong testing data and got the correct results after modification. Thank you so much.

hello, sorry to ask you such a basic question. Excuse me, how to calculate psnr with matlab, is the input a picture? How many sets of pictures are used to calculate psnr and ssim?
